// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZliNO9Ng4loEvY-TAgckmGUN8MPZuSXw',
    appId: '1:783634576451:web:1f4e82c0ca7bebf05810f6',
    messagingSenderId: '783634576451',
    projectId: 'jal-seva-f59e2',
    authDomain: 'jal-seva-f59e2.firebaseapp.com',
    storageBucket: 'jal-seva-f59e2.firebasestorage.app',
    measurementId: 'G-J857L61L4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjUTBEBphPViJkFt1DacVYHl6GkZWzW4',
    appId: '1:783634576451:android:9d56d45b9d215e335810f6',
    messagingSenderId: '783634576451',
    projectId: 'jal-seva-f59e2',
    storageBucket: 'jal-seva-f59e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOArYxNw8lQBhtx4RJjccR9_SUB8kcDZA',
    appId: '1:783634576451:ios:0b93f23532c2e62a5810f6',
    messagingSenderId: '783634576451',
    projectId: 'jal-seva-f59e2',
    storageBucket: 'jal-seva-f59e2.firebasestorage.app',
    iosBundleId: 'com.example.jalSeva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOArYxNw8lQBhtx4RJjccR9_SUB8kcDZA',
    appId: '1:783634576451:ios:0b93f23532c2e62a5810f6',
    messagingSenderId: '783634576451',
    projectId: 'jal-seva-f59e2',
    storageBucket: 'jal-seva-f59e2.firebasestorage.app',
    iosBundleId: 'com.example.jalSeva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZliNO9Ng4loEvY-TAgckmGUN8MPZuSXw',
    appId: '1:783634576451:web:187dabbbb2da9e1b5810f6',
    messagingSenderId: '783634576451',
    projectId: 'jal-seva-f59e2',
    authDomain: 'jal-seva-f59e2.firebaseapp.com',
    storageBucket: 'jal-seva-f59e2.firebasestorage.app',
    measurementId: 'G-E3N75R375T',
  );
}
